import { writeFileSync } from 'fs'

const data = [
  [1, 'Al-Fatihah', 'الفاتحة', 'The Opening', 7, 'Makki', 1],
  [2, 'Al-Baqarah', 'البقرة', 'The Cow', 286, 'Madni', 1],
  [3, "Ali 'Imran", 'آل عمران', 'Family of Imran', 200, 'Madni', 3],
  [4, 'An-Nisa', 'النساء', 'The Women', 176, 'Madni', 4],
  [5, "Al-Ma'idah", 'المائدة', 'The Table Spread', 120, 'Madni', 6],
  [6, "Al-An'am", 'الأنعام', 'The Cattle', 165, 'Makki', 7],
  [7, "Al-A'raf", 'الأعراف', 'The Heights', 206, 'Makki', 8],
  [8, 'Al-Anfal', 'الأنفال', 'The Spoils of War', 75, 'Madni', 9],
  [9, 'At-Tawbah', 'التوبة', 'The Repentance', 129, 'Madni', 10],
  [10, 'Yunus', 'يونس', 'Jonah', 109, 'Makki', 11],
  [11, 'Hud', 'هود', 'Hud', 123, 'Makki', 11],
  [12, 'Yusuf', 'يوسف', 'Joseph', 111, 'Makki', 12],
  [13, "Ar-Ra'd", 'الرعد', 'The Thunder', 43, 'Madni', 13],
  [14, 'Ibrahim', 'إبراهيم', 'Abraham', 52, 'Makki', 13],
  [15, 'Al-Hijr', 'الحجر', 'The Rocky Tract', 99, 'Makki', 14],
  [16, 'An-Nahl', 'النحل', 'The Bee', 128, 'Makki', 14],
  [17, 'Al-Isra', 'الإسراء', 'The Night Journey', 111, 'Makki', 15],
  [18, 'Al-Kahf', 'الكهف', 'The Cave', 110, 'Makki', 15],
  [19, 'Maryam', 'مريم', 'Mary', 98, 'Makki', 16],
  [20, 'Ta-Ha', 'طه', 'Ta-Ha', 135, 'Makki', 16],
  [21, 'Al-Anbiya', 'الأنبياء', 'The Prophets', 112, 'Makki', 17],
  [22, 'Al-Hajj', 'الحج', 'The Pilgrimage', 78, 'Madni', 17],
  [23, "Al-Mu'minun", 'المؤمنون', 'The Believers', 118, 'Makki', 18],
  [24, 'An-Nur', 'النور', 'The Light', 64, 'Madni', 18],
  [25, 'Al-Furqan', 'الفرقان', 'The Criterion', 77, 'Makki', 18],
  [26, "Ash-Shu'ara", 'الشعراء', 'The Poets', 227, 'Makki', 19],
  [27, 'An-Naml', 'النمل', 'The Ant', 93, 'Makki', 19],
  [28, 'Al-Qasas', 'القصص', 'The Stories', 88, 'Makki', 20],
  [29, "Al-'Ankabut", 'العنكبوت', 'The Spider', 69, 'Makki', 20],
  [30, 'Ar-Rum', 'الروم', 'The Romans', 60, 'Makki', 21],
  [31, 'Luqman', 'لقمان', 'Luqman', 34, 'Makki', 21],
  [32, 'As-Sajdah', 'السجدة', 'The Prostration', 30, 'Makki', 21],
  [33, 'Al-Ahzab', 'الأحزاب', 'The Combined Forces', 73, 'Madni', 21],
  [34, 'Saba', 'سبأ', 'Sheba', 54, 'Makki', 22],
  [35, 'Fatir', 'فاطر', 'The Originator', 45, 'Makki', 22],
  [36, 'Ya-Sin', 'يس', 'Ya Sin', 83, 'Makki', 22],
  [37, 'As-Saffat', 'الصافات', 'Those Who Set The Ranks', 182, 'Makki', 23],
  [38, 'Sad', 'ص', 'The Letter Sad', 88, 'Makki', 23],
  [39, 'Az-Zumar', 'الزمر', 'The Troops', 75, 'Makki', 23],
  [40, 'Ghafir', 'غافر', 'The Forgiver', 85, 'Makki', 24],
  [41, 'Fussilat', 'فصلت', 'Explained in Detail', 54, 'Makki', 24],
  [42, 'Ash-Shuraa', 'الشورى', 'The Consultation', 53, 'Makki', 25],
  [43, 'Az-Zukhruf', 'الزخرف', 'The Ornaments of Gold', 89, 'Makki', 25],
  [44, 'Ad-Dukhan', 'الدخان', 'The Smoke', 59, 'Makki', 25],
  [45, 'Al-Jathiyah', 'الجاثية', 'The Crouching', 37, 'Makki', 25],
  [46, 'Al-Ahqaf', 'الأحقاف', 'The Wind-Curved Sandhills', 35, 'Makki', 26],
  [47, 'Muhammad', 'محمد', 'Muhammad', 38, 'Madni', 26],
  [48, 'Al-Fath', 'الفتح', 'The Victory', 29, 'Madni', 26],
  [49, 'Al-Hujurat', 'الحجرات', 'The Rooms', 18, 'Madni', 26],
  [50, 'Qaf', 'ق', 'The Letter Qaf', 45, 'Makki', 26],
  [51, 'Adh-Dhariyat', 'الذاريات', 'The Winnowing Winds', 60, 'Makki', 26],
  [52, 'At-Tur', 'الطور', 'The Mount', 49, 'Makki', 27],
  [53, 'An-Najm', 'النجم', 'The Star', 62, 'Makki', 27],
  [54, 'Al-Qamar', 'القمر', 'The Moon', 55, 'Makki', 27],
  [55, 'Ar-Rahman', 'الرحمن', 'The Beneficent', 78, 'Madni', 27],
  [56, "Al-Waqi'ah", 'الواقعة', 'The Inevitable', 96, 'Makki', 27],
  [57, 'Al-Hadid', 'الحديد', 'The Iron', 29, 'Madni', 27],
  [58, 'Al-Mujadila', 'المجادلة', 'The Pleading Woman', 22, 'Madni', 28],
  [59, 'Al-Hashr', 'الحشر', 'The Exile', 24, 'Madni', 28],
  [60, 'Al-Mumtahanah', 'الممتحنة', 'She That Is To Be Examined', 13, 'Madni', 28],
  [61, 'As-Saf', 'الصف', 'The Ranks', 14, 'Madni', 28],
  [62, "Al-Jumu'ah", 'الجمعة', 'The Congregation', 11, 'Madni', 28],
  [63, 'Al-Munafiqun', 'المنافقون', 'The Hypocrites', 11, 'Madni', 28],
  [64, 'At-Taghabun', 'التغابن', 'The Mutual Disillusion', 18, 'Madni', 28],
  [65, 'At-Talaq', 'الطلاق', 'The Divorce', 12, 'Madni', 28],
  [66, 'At-Tahrim', 'التحريم', 'The Prohibition', 12, 'Madni', 28],
  [67, 'Al-Mulk', 'الملك', 'The Sovereignty', 30, 'Makki', 29],
  [68, 'Al-Qalam', 'القلم', 'The Pen', 52, 'Makki', 29],
  [69, 'Al-Haqqah', 'الحاقة', 'The Reality', 52, 'Makki', 29],
  [70, "Al-Ma'arij", 'المعارج', 'The Ascending Stairways', 44, 'Makki', 29],
  [71, 'Nuh', 'نوح', 'Noah', 28, 'Makki', 29],
  [72, 'Al-Jinn', 'الجن', 'The Jinn', 28, 'Makki', 29],
  [73, 'Al-Muzzammil', 'المزمل', 'The Enshrouded One', 20, 'Makki', 29],
  [74, 'Al-Muddaththir', 'المدثر', 'The Cloaked One', 56, 'Makki', 29],
  [75, 'Al-Qiyamah', 'القيامة', 'The Resurrection', 40, 'Makki', 29],
  [76, 'Al-Insan', 'الإنسان', 'The Man', 31, 'Madni', 29],
  [77, 'Al-Mursalat', 'المرسلات', 'The Emissaries', 50, 'Makki', 29],
  [78, 'An-Naba', 'النبأ', 'The Tidings', 40, 'Makki', 30],
  [79, "An-Nazi'at", 'النازعات', 'Those Who Drag Forth', 46, 'Makki', 30],
  [80, 'Abasa', 'عبس', 'He Frowned', 42, 'Makki', 30],
  [81, 'At-Takwir', 'التكوير', 'The Overthrowing', 29, 'Makki', 30],
  [82, 'Al-Infitar', 'الانفطار', 'The Cleaving', 19, 'Makki', 30],
  [83, 'Al-Mutaffifin', 'المطففين', 'The Defrauding', 36, 'Makki', 30],
  [84, 'Al-Inshiqaq', 'الانشقاق', 'The Sundering', 25, 'Makki', 30],
  [85, 'Al-Buruj', 'البروج', 'The Mansions of the Stars', 22, 'Makki', 30],
  [86, 'At-Tariq', 'الطارق', 'The Nightcommer', 17, 'Makki', 30],
  [87, "Al-A'la", 'الأعلى', 'The Most High', 19, 'Makki', 30],
  [88, 'Al-Ghashiyah', 'الغاشية', 'The Overwhelming', 26, 'Makki', 30],
  [89, 'Al-Fajr', 'الفجر', 'The Dawn', 30, 'Makki', 30],
  [90, 'Al-Balad', 'البلد', 'The City', 20, 'Makki', 30],
  [91, 'Ash-Shams', 'الشمس', 'The Sun', 15, 'Makki', 30],
  [92, 'Al-Layl', 'الليل', 'The Night', 21, 'Makki', 30],
  [93, 'Ad-Duhaa', 'الضحى', 'The Morning Hours', 11, 'Makki', 30],
  [94, 'Ash-Sharh', 'الشرح', 'The Relief', 8, 'Makki', 30],
  [95, 'At-Tin', 'التين', 'The Fig', 8, 'Makki', 30],
  [96, "Al-'Alaq", 'العلق', 'The Clot', 19, 'Makki', 30],
  [97, 'Al-Qadr', 'القدر', 'The Power', 5, 'Makki', 30],
  [98, 'Al-Bayyinah', 'البينة', 'The Clear Proof', 8, 'Madni', 30],
  [99, 'Az-Zalzalah', 'الزلزلة', 'The Earthquake', 8, 'Madni', 30],
  [100, "Al-'Adiyat", 'العاديات', 'The Courser', 11, 'Makki', 30],
  [101, "Al-Qari'ah", 'القارعة', 'The Calamity', 11, 'Makki', 30],
  [102, 'At-Takathur', 'التكاثر', 'The Rivalry in World Increase', 8, 'Makki', 30],
  [103, "Al-'Asr", 'العصر', 'The Declining Day', 3, 'Makki', 30],
  [104, 'Al-Humazah', 'الهمزة', 'The Traducer', 9, 'Makki', 30],
  [105, 'Al-Fil', 'الفيل', 'The Elephant', 5, 'Makki', 30],
  [106, 'Quraysh', 'قريش', 'Quraysh', 4, 'Makki', 30],
  [107, "Al-Ma'un", 'الماعون', 'The Small Kindnesses', 7, 'Makki', 30],
  [108, 'Al-Kawthar', 'الكوثر', 'The Abundance', 3, 'Makki', 30],
  [109, 'Al-Kafirun', 'الكافرون', 'The Disbelievers', 6, 'Makki', 30],
  [110, 'An-Nasr', 'النصر', 'The Divine Support', 3, 'Madni', 30],
  [111, 'Al-Masad', 'المسد', 'The Palm Fiber', 5, 'Makki', 30],
  [112, 'Al-Ikhlas', 'الإخلاص', 'The Sincerity', 4, 'Makki', 30],
  [113, 'Al-Falaq', 'الفلق', 'The Daybreak', 5, 'Makki', 30],
  [114, 'An-Nas', 'الناس', 'Mankind', 6, 'Makki', 30],
]

if (data.length !== 114) {
  throw new Error(`Expected 114 surahs, got ${data.length}`)
}

const surahs = data.map(([num, name, ar, meaning, verses, type, juz]) => ({
  num,
  name,
  ar,
  meaning,
  verses,
  type,
  juz,
}))

writeFileSync(new URL('../src/data/surahs.json', import.meta.url), JSON.stringify(surahs))
console.log('wrote', surahs.length, 'surahs')
